image: Visual Studio 2017

platform: 
  - x86
  - x64
  
configuration: 
  - Release
  
build_script:
  - msbuild
  
after_build: 
  - git config --global user.email "meltedspark@gmail.com"
  - git config --global user.name "Evgeny Barabanov"
  - git add bin/**/*.dll
  - git commit -m "Build success for Windows [skip ci]"
  - git remote rm origin
  - git remote add origin https://%SIMPLE_LIB_TOKEN%@github.com/meltedspark/electron-angular-native-simplelib.git
  - git push origin HEAD:%APPVEYOR_REPO_BRANCH%
